//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Projects.MySociety.WCFServiceClient.ResidentSvcReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatBO", Namespace="http://schemas.datacontract.org/2004/07/HRS.Projects.MySociety.BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class FlatBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short FlatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlatNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfResidentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short FlatId {
            get {
                return this.FlatIdField;
            }
            set {
                if ((this.FlatIdField.Equals(value) != true)) {
                    this.FlatIdField = value;
                    this.RaisePropertyChanged("FlatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlatName {
            get {
                return this.FlatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FlatNameField, value) != true)) {
                    this.FlatNameField = value;
                    this.RaisePropertyChanged("FlatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfResidents {
            get {
                return this.NoOfResidentsField;
            }
            set {
                if ((this.NoOfResidentsField.Equals(value) != true)) {
                    this.NoOfResidentsField = value;
                    this.RaisePropertyChanged("NoOfResidents");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResidentSvcReference.IResidentSvc")]
    public interface IResidentSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidentSvc/GetFlatDetails", ReplyAction="http://tempuri.org/IResidentSvc/GetFlatDetailsResponse")]
        HRS.Projects.MySociety.WCFServiceClient.ResidentSvcReference.FlatBO[] GetFlatDetails(int societyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidentSvc/GetFlatDetails", ReplyAction="http://tempuri.org/IResidentSvc/GetFlatDetailsResponse")]
        System.Threading.Tasks.Task<HRS.Projects.MySociety.WCFServiceClient.ResidentSvcReference.FlatBO[]> GetFlatDetailsAsync(int societyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidentSvc/TestException", ReplyAction="http://tempuri.org/IResidentSvc/TestExceptionResponse")]
        string TestException();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResidentSvc/TestException", ReplyAction="http://tempuri.org/IResidentSvc/TestExceptionResponse")]
        System.Threading.Tasks.Task<string> TestExceptionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResidentSvcChannel : HRS.Projects.MySociety.WCFServiceClient.ResidentSvcReference.IResidentSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResidentSvcClient : System.ServiceModel.ClientBase<HRS.Projects.MySociety.WCFServiceClient.ResidentSvcReference.IResidentSvc>, HRS.Projects.MySociety.WCFServiceClient.ResidentSvcReference.IResidentSvc {
        
        public ResidentSvcClient() {
        }
        
        public ResidentSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResidentSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResidentSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResidentSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HRS.Projects.MySociety.WCFServiceClient.ResidentSvcReference.FlatBO[] GetFlatDetails(int societyId) {
            return base.Channel.GetFlatDetails(societyId);
        }
        
        public System.Threading.Tasks.Task<HRS.Projects.MySociety.WCFServiceClient.ResidentSvcReference.FlatBO[]> GetFlatDetailsAsync(int societyId) {
            return base.Channel.GetFlatDetailsAsync(societyId);
        }
        
        public string TestException() {
            return base.Channel.TestException();
        }
        
        public System.Threading.Tasks.Task<string> TestExceptionAsync() {
            return base.Channel.TestExceptionAsync();
        }
    }
}
