//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Projects.MySociety.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bldg
    {
        public Bldg()
        {
            this.Wings = new HashSet<Wing>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
        public byte NoOfWings { get; set; }
        public byte NoOfFloors { get; set; }
        public string Comment { get; set; }
        public short SocietyId { get; set; }
    
        public virtual Society Society { get; set; }
        public virtual ICollection<Wing> Wings { get; set; }
    }
}
