//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Projects.MySociety.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public Flat()
        {
            this.People = new HashSet<Person>();
        }
    
        public short Id { get; set; }
        public string FlatNo { get; set; }
        public Nullable<byte> NoOfResidents { get; set; }
        public Nullable<short> WingId { get; set; }
    
        public virtual Wing Wing { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
