//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Projects.MySociety.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Relations = new HashSet<Relation>();
            this.Relations1 = new HashSet<Relation>();
        }
    
        public short Id { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public System.DateTime Dob { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsPrimaryOwner { get; set; }
        public Nullable<bool> IsSecOwner { get; set; }
        public short FlatId { get; set; }
        public string EmailId { get; set; }
        public string Mobile { get; set; }
        public string Landline { get; set; }
        public string AlternateAddr { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual ICollection<Relation> Relations { get; set; }
        public virtual ICollection<Relation> Relations1 { get; set; }
    }
}
