//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Projects.MySociety.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wing
    {
        public Wing()
        {
            this.Flats = new HashSet<Flat>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<short> BldgId { get; set; }
    
        public virtual Bldg Bldg { get; set; }
        public virtual ICollection<Flat> Flats { get; set; }
    }
}
